version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container-teste1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app-network

  api:
    image: laranjeirajuliano/campus-connect:latest
    container_name: api-container
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - postgres

networks:
  app-network:
    driver: bridge
