name: ImagePull&Push

on:
  push:
    branches:
      - main
      - developer
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1

      - name: Autenticação no Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{secrets.DOCKERUSER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: construção imagem Docker
        uses: docker/build-push-action@v6.9.0
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            laranjeirajuliano/campus-connect:${{github.run_number}}
            laranjeirajuliano/campus-connect:latest
